### ISSUE TITLE
What's wrong? I have opened the VPN in global mode.

### ISSUE THREAD

**Issue by CaiXunchao** [0xacx/chatGPT-shell-cli#49] opened 2023-03-20 09:49 UTC
curl: (7) Failed to connect to api.openai.com port 443: Operation timed out
Your request to Open AI API failed:

**Comment by 0xacx** [comment] 2023-03-24 14:41
@CaiXunchao I am closing this issue as it is a failure that is not caused by the script itself. I hope you figured it out.

**Closed by 0xacx** 2023-03-24 14:41 UTC
