### ISSUE TITLE
Asterisk in the reponse will be replaced by the concatenation of all file names under current directory.

### ISSUE THREAD

**Issue by dilatedpupils** [0xacx/chatGPT-shell-cli#31] opened 2023-03-07 22:09 UTC
On my Linux machine:

```
root@ubuntu-NY:~# ls
Downloads  audio  chatgptmd  snap
```

When gpt returns something including `*`, the result where it appears will be replaced by he concatenation of all file names under current directory:

![image](https://user-images.githubusercontent.com/102026736/223564661-7ec6ca03-ffdb-486e-abe3-378b64554b44.png)
![image](https://user-images.githubusercontent.com/102026736/223564752-da36f687-7707-4aa1-8c2f-469b1ab89ff1.png)

**Comment by mountaineerbr** [comment] 2023-03-08 19:48
Maybe the problem is with variable substitutions that are unquoted throughout the script, in such cases as `response_data=$2`.

**Comment by 0xacx** [comment] 2023-03-10 11:43
I thought that simply escaping the asterisk would fix it but turns out it's a bit different: https://stackoverflow.com/questions/102049/how-do-i-escape-the-wildcard-asterisk-character-in-bash Fixed in #34

**Closed by 0xacx** 2023-03-10 11:43 UTC
